### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Emmanuelaaron** [abdelp/using-bootstrap#1]
- Consider removing comments from your code
- Validate the CSS file using the stickler
- Consider floating the images in the more stories section to make the text wrap around
- Use a min-height and min-width for the image in the newsletter subscription section.

**Comment by abdelp** [comment]
- Comments removed from css and html files
- CSS and HTML files validated
- Images floated to wrap the text around.
- Used min-height for the image in newsletter section.


Thank you very much for your suggestions.
